zookeeper:
  image: cpsot/zookeeper:latest
  ports: 
    - "2181:2181"

nimbus:
  image: cpsot/storm-nimbus:latest
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
  links: 
    - zookeeper:zk

supervisor:
  image: cpsot/storm-supervisor:latest
  ports:
    - "8000:8000"
  links: 
    - nimbus:nimbus
    - zookeeper:zk

ui:
  image: cpsot/storm-ui:latest
  ports:
    - "8088:8080"
  links: 
    - nimbus:nimbus
    - zookeeper:zk

kafka:
  image: cpsot/kafka:latest
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_CREATE_TOPICS: "CPSOT:1:1"
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock

tornado:
  image: cpsot/websocket:latest
  ports:
    - "8686:8585"

mongo:
  image: cpsot/mongo:latest
  ports:
    - "27017:27017"

mongo-api:
  image: cpsot/mongo-api:latest
  ports:
    - "8080:8080"
  environment:
    DOCKER_HOST_IP: 192.168.99.100

event-dispatcher:
  image: cpsot/event-dispatcher:latest
  environment:
    DOCKER_HOST_IP: 192.168.99.100
    KAFKA_TOPIC_NAME: CPSOT
